apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app-container
    image: gcr.io/k3d-yk/demo:v1.0.0
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: DB_USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: app-secrets
          key: DB_PASSWORD
