apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-backup
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo Backup task
          restartPolicy: OnFailure
