apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app
      image: gcr.io/k3d-yk/demo:v1.0.0
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: app-pvc