apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
